# Generated by Django 5.2.12 on 2026-04-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_is_email_verified_user_is_phone_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='banner',
            name='core_banner_is_acti_99fbb2_idx',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='updated_at',
        ),
    ]
