# Generated by Django 5.2.12 on 2026-04-15 11:21

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 11, 20, 17, 986699, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active'], name='core_banner_is_acti_fe56b3_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['start_date', 'end_date'], name='core_banner_start_d_bb0bc8_idx'),
        ),
    ]
