# Generated by Django 5.2.12 on 2026-04-15 11:25

from django.db import migrations, models
import django.utils.timezone
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_banner_options_banner_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(
                default=lambda: django.utils.timezone.now() + timedelta(days=7)
            ),
        ),
    ]