# Generated by Django 5.2.12 on 2026-04-15 11:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_banner_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(default=core.models.default_end_date),
        ),
    ]
