# Generated by Django 5.2.12 on 2026-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_banner_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(default='Explore', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='sub_heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
