# Generated by Django 5.2.11 on 2026-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
