# Generated by Django 5.2.11 on 2026-02-26 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellerprofile',
            name='seller_sell_is_veri_38db58_idx',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_verified',
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['verification_status'], name='seller_sell_verific_c43e3f_idx'),
        ),
    ]
