from django.urls import path
from django.views.generic import TemplateView
from . import views
urlpatterns = [
    path("login/",views.login_view,name="login"),
    path("register/",views.register_view,name="register"),
    path("verify-method/",views.choose_verification,name="choose_verification"),
    path("resend-otp/",views.resend_otp,name="resend_otp"),
    path("verify-email/",views.email_verification,name="email_verification"),
    path("verify-phone/",views.phone_verification,name="phone_verification"),
    path("verify-otp/",views.verify_otp,name="verify_otp"),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("verify-reset-otp/", views.verify_reset_otp, name="verify_reset_otp"),
    path("reset-password/", views.reset_password, name="reset_password"),
    path("",views.home_view,name="home"),
    path("logout/",views.logout_view,name="logout"),
    path("products/", views.all_products, name="all_products"),
    path("products/", views.all_products, name="product_list"),
    path("home/category/<str:category_slug>/", views.category_view,name="category"), 
    path("products/category/subcategory/<str:subcategory_slug>/", views.subcategory_view, name="subcategory"), 
    path("products/subcategory/<str:slug>/", views.product_detail,name="product_details"),  
    path("search-suggestions/", views.search_suggestions, name="search_suggestions"),
    path("new-arrivals/", views.new_arrivals, name="new_arrivals"),
    path("trending/", views.trending_products_page, name="trending"),
    path('our-story/', TemplateView.as_view(template_name='core/dummy/our_story.html'), name='our_story'),
    path('faq/', TemplateView.as_view(template_name='core/dummy/faq.html'), name='faq'),
    path('contact/', TemplateView.as_view(template_name='core/dummy/contactus.html'), name='contactus'),
    path('shipping-returns/', TemplateView.as_view(template_name='core/dummy/shipping_returns.html'), name='shipping_returns'),
    path('privacy-policy/', TemplateView.as_view(template_name='core/dummy/legal.html'), name='privacy'),
    path('blog/', TemplateView.as_view(template_name='core/dummy/blog.html'), name='blog'),
    path('returns-policy/', TemplateView.as_view(template_name='core/dummy/returns_policy.html'), name='return_Policy'),
    path('terms-conditions/', TemplateView.as_view(template_name='core/dummy/terms_conditions.html'), name='terms_conditions'),
    ]